import csv
import tempfile
import unittest
from pathlib import Path

from scripts.build_job_tier_mediation_table import read_rows, render_table


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "analysis/paper_replication/figuresNtables"


class JobTierMediationTests(unittest.TestCase):
    def test_preferred_baseline_and_joint_null_are_preserved(self):
        # Frozen preferred Table 2 outputs, independently generated by run_twfe.
        expected = {
            "ln_parados": (0.012061944129354, 0.0168132599278554, 0.0026627015, 31122),
            "ln_contratos": (0.0144644656032463, 0.0129039305565127, 0.031847086, 30786),
        }
        rows = read_rows(RESULTS / "job_tier_mediation_estimates.csv")
        pre = read_rows(RESULTS / "job_tier_mediation_pretrends.csv")
        for outcome, (adjustment, later, p, n) in expected.items():
            selected = {r["term"]: r for r in rows if r["outcome"] == outcome and r["specification"] == "baseline"}
            self.assertEqual(float(selected["dose_adjustment"]["estimate"]), adjustment)
            self.assertEqual(float(selected["dose_later"]["estimate"]), later)
            self.assertEqual(int(selected["dose_adjustment"]["observations"]), n)
            diagnostic = next(r for r in pre if r["outcome"] == outcome and r["specification"] == "baseline")
            self.assertEqual(float(diagnostic["p_value"]), p)
            self.assertEqual(int(diagnostic["df_num"]), 20)

    def test_renderer_rejects_a_changed_comparison_sample(self):
        with tempfile.TemporaryDirectory() as directory:
            estimates = Path(directory) / "estimates.csv"
            rows = read_rows(RESULTS / "job_tier_mediation_estimates.csv")
            adjusted = next(r for r in rows if r["specification"] == "month_fe")
            adjusted["observations"] = "30000"
            with estimates.open("w", newline="", encoding="utf-8") as handle:
                writer = csv.DictWriter(handle, fieldnames=rows[0].keys())
                writer.writeheader()
                writer.writerows(rows)
            with self.assertRaisesRegex(ValueError, "samples differ"):
                render_table(estimates, RESULTS / "job_tier_mediation_pretrends.csv")


if __name__ == "__main__":
    unittest.main()
